openapi: 3.0.0
info:
  title: AI Chatbot API
  version: 1.0.0
  description: API for AI-powered todo chatbot functionality

paths:
  /api/{user_id}/chat:
    post:
      summary: Process chat message and return AI response
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation_id:
                  type: integer
                  description: Optional conversation identifier
                message:
                  type: string
                  description: User's chat message
              required:
                - message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: integer
                    description: Identifier for the conversation
                  response:
                    type: string
                    description: AI-generated response
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the tool called
                        arguments:
                          type: object
                          description: Arguments passed to the tool
                required:
                  - conversation_id
                  - response
                  - tool_calls
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/{user_id}/conversations:
    get:
      summary: Get list of user's conversations
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'

  /api/{user_id}/conversations/{conversation_id}/messages:
    get:
      summary: Get messages for a specific conversation
      parameters:
        - name: user_id
          in: path
          required: true
          description: User identifier
          schema:
            type: string
        - name: conversation_id
          in: path
          required: true
          description: Conversation identifier
          schema:
            type: integer
      responses:
        '200':
          description: List of messages in the conversation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'

components:
  schemas:
    Conversation:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the conversation
        user_id:
          type: string
          description: User identifier
        created_at:
          type: string
          format: date-time
          description: Timestamp when conversation was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when conversation was last updated
      required:
        - id
        - user_id
        - created_at
        - updated_at

    Message:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the message
        conversation_id:
          type: integer
          description: Conversation identifier
        role:
          type: string
          enum: [user, assistant]
          description: Role of the message sender
        content:
          type: string
          description: Content of the message
        created_at:
          type: string
          format: date-time
          description: Timestamp when message was created
      required:
        - id
        - conversation_id
        - role
        - content
        - created_at